CREATE TABLE `server_info` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `GAME_ID` bigint(20) NOT NULL,
  `AREA_ID` bigint(20) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DATA` text NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `APP_ID` (`AREA_ID`),
  KEY `NAME` (`NAME`),
  KEY `GAME_ID` (`GAME_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=26 DEFAULT CHARSET=utf8

CREATE TABLE `user` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) CHARACTER SET gbk NOT NULL,
  `PASSWORD` varchar(25) CHARACTER SET gbk NOT NULL,
  `REGISTER_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ROLE_PRIVILEGE` text CHARACTER SET gbk NOT NULL,
  `GAME_INFO` text NOT NULL,
  `SESSION` text NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME_4` (`NAME`),
  KEY `NAME` (`NAME`),
  KEY `NAME_2` (`NAME`),
  KEY `NAME_3` (`NAME`),
  KEY `NAME_5` (`NAME`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8